Copy constructor chapter
UWCubeSat/cpp-boot-camp pull request #8
Opened 2022-12-24 15:57 UTC by zeddie888

2022-12-27 06:11 UTC, nguy8tri commented on README.md
> +Also  a nice read for new [Husky Satellite Lab](https://huskysat.org/) members!
space!!!

2022-12-27 06:23 UTC, nguy8tri requested changes
For some reason, I cannot comment on some of the cctor stuff, so I'll say it here. It looks great, but at the last few sections, its a bit unclear that 1 comes from the heap. I think when you state `Let's assume rank is a pointer to an int allocated on the heap`, it makes it more ambiguous, but this is not needed since `new` "automatically" allocates to the heap, as you'll see in my section (Its not like I just learned this 3 hours ago)! But in general, you can never guarantee that anything points to the heap unless you put an allocating statement (i.e. `malloc()` or `new`) in your constructor for that specific variable, so maybe also make a note about this, because this becomes an issue in the destructor I believe. But great job, your things look good!

2022-12-27 06:26 UTC, zeddie888 commented on README.md
> +Also  a nice read for new [Husky Satellite Lab](https://huskysat.org/) members!
😭😭😭😭😭😭😭😭

2022-12-29 01:25 UTC, nguy8tri approved these changes
Perfetto!

2022-12-29 01:26 UTC, merged